
spring:
  datasource: # AWS RDS 연동
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://seb40-pre-038.cpw41kqdm29i.ap-northeast-2.rds.amazonaws.com:53306/test?serverTimezone=Asia/Seoul&characterEncoding=UTF-8  # JDBC URL
    username:
    password:
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update  # 스키마 자동 생성 - 기존 테이블 유지한 채 변경사항 반영
    show-sql: true  # SQL 쿼리 출력
server:
  servlet:
    encoding:
      force-response: true
mail:
  address:
    admin: admin@email.com
jwt:
  secret-key: temporary1111potato1111temporary1111potato # ${JWT_SECRET_KEY}
  access-token-expiration-minutes: 30  # minutes
  refresh-token-expiration-minutes: 420
config:
  domain: http://seb40-pre-038.cpw41kqdm29i.ap-northeast-2.rds.amazonaws.com
